### ISSUE TITLE
Make building things more intuitive

### ISSUE THREAD

**Issue by heroin-moose** [PucklaJ/samurai-select#1]
`go build` fails because of no go.sum, so something like this Makefile would be nice to have:

```
smel: tidy
        go build -v -o $@

tidy:
        go mod tidy
```

**Comment by heroin-moose** [comment]
However, perhaps it would be easier just to commit go.sum.

**Comment by PucklaJ** [comment]
This must be new because if I remember correctly `go build` did call tidy and create `go.sum`. Thanks for letting me know. I committed go.sum.
